services:
  # Backend Service - Lightweight with proper networking
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: uni_backend
    environment:
      - DEBUG=True
      - SECRET_KEY=dev-secret-key-for-friends
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,http://0.0.0.0:3000
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,0.0.0.0
    volumes:
      - ./backend:/app
      - vector_cache:/app/vector_store_cache
    ports:
      - "8000:8000"
    networks:
      - uni_network
    restart: unless-stopped
    # Resource limits to prevent system lag
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Frontend Service - Lightweight with proper networking
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: uni_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - uni_network
    restart: unless-stopped
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

volumes:
  vector_cache:
    driver: local

networks:
  uni_network:
    driver: bridge
    # Ensure containers can communicate and be accessed from host
    ipam:
      config:
        - subnet: 172.20.0.0/16 