# Generated by Django 5.2.4 on 2025-07-22 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_id', models.IntegerField(unique=True)),
                ('university_name', models.CharField(max_length=255)),
                ('university_slug', models.CharField(max_length=255)),
                ('university_global_rank', models.FloatField(blank=True, null=True)),
                ('location_name', models.CharField(max_length=255)),
                ('country_name', models.CharField(max_length=255)),
                ('country_currency', models.CharField(max_length=10)),
                ('university_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_course_id', models.IntegerField(unique=True)),
                ('university_course_name', models.CharField(max_length=255)),
                ('course_program_label', models.CharField(max_length=255)),
                ('parent_course_name', models.CharField(max_length=255)),
                ('university_course_tuition_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('university_course_tuition_local', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('university_courses_credential', models.CharField(max_length=50)),
                ('program_level', models.IntegerField()),
                ('program_type', models.CharField(max_length=50)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='recommendations.university')),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('desired_program', models.CharField(max_length=255)),
                ('program_level', models.CharField(max_length=50)),
                ('program_type', models.CharField(max_length=50)),
                ('preferred_countries', models.JSONField(default=list)),
                ('preferred_locations', models.JSONField(default=list)),
                ('max_tuition_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_currency', models.CharField(default='USD', max_length=10)),
                ('min_global_rank', models.IntegerField(blank=True, null=True)),
                ('university_types', models.JSONField(default=list)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('test_scores', models.JSONField(default=dict)),
                ('additional_preferences', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField()),
                ('match_percentage', models.FloatField()),
                ('reasoning', models.TextField()),
                ('llm_reasoning', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.course')),
                ('user_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendations.userpreference')),
            ],
            options={
                'verbose_name_plural': 'Recommendations',
                'ordering': ['-relevance_score'],
            },
        ),
    ]
