# Generated by Django 5.2.4 on 2025-07-22 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_program', models.CharField(max_length=255)),
                ('program_level', models.CharField(max_length=50)),
                ('program_type', models.CharField(max_length=50)),
                ('preferred_countries', models.JSONField(default=list)),
                ('preferred_locations', models.JSONField(default=list)),
                ('max_tuition_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_currency', models.CharField(default='USD', max_length=10)),
                ('min_global_rank', models.IntegerField(blank=True, null=True)),
                ('university_types', models.JSONField(default=list)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('test_scores', models.JSONField(default=dict)),
                ('additional_preferences', models.TextField(blank=True)),
                ('recommendations_count', models.IntegerField(default=0)),
                ('search_results', models.JSONField(default=list)),
                ('search_duration_ms', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
