# Generated by Django 5.2.4 on 2025-07-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_usersubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='university',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='course',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='user_preference',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.DeleteModel(
            name='University',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
